[project]
name = "debuzz"
version = "0.1.0"
description = "The universal buzzword sanitiser"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypercorn>=0.17.3",
    "quart>=0.20.0",
    "textstat>=0.7.5",
]
